format = "$character$directory$git_branch$git_commit$git_status$env_var"
# Don't print a new line at the start of the prompt
# add_newline = true
# 

[directory]
style = "cyan"
truncation_symbol = ".../"

# Replace the "❯ " symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = " [](green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = " [](red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[time]
disabled = true

[cmd_duration]
min_time = 1
format = "[~](cyan)[$duration]($style)"
disabled = false

[status]
symbol = "🔴"
format = '[\[$symbol$status_common_meaning$status_signal_name$status_maybe_int\]]($style)'
map_symbol = true
disabled = false

[aws]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "
